webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Панель администратора'
    return render_template('admin/index.html', page_title=title)

webapp/object/views.py
import os
from flask import Blueprint, render_template, redirect, url_for, flash
from webapp.object.forms import AddingLotForm
from webapp.db import db
from webapp.object.models import Object
from webapp.user.models import User

blueprint = Blueprint('lots', __name__, url_prefix='/lots')

UPLOAD_FOLDER = './webapp/uploads'

@blueprint.route('/')
def lots():
    page_title = "Лоты на продажу"
    object_list = Object.query.all()
    #object_name = Object.object_name
    #object_description = Object.description
    #object_img = Object.img
    #object_starting_price = Object.starting_price
    #object_email = Object.email
    return render_template('object/lots.html', object_list=object_list, page_title=page_title) #object_name=object_name, object_description=object_description, object_img=object_img, object_starting_price=object_starting_price, object_email=object_email)


@blueprint.route('/adding-lots')
def adding_lots():
    form = AddingLotForm()
    page_title = "Add lots"
    return render_template('object/adding_lots.html', page_title=page_title, form=form)


@blueprint.route('/process-add', methods=['POST'])
def process_add():
    form = AddingLotForm()
    if form.validate_on_submit():
        new_object = Object(object_name=form.object_name.data, description=form.description.data, starting_price=form.starting_price.data, email=form.email.data)
        db.session.add(new_object)
        db.session.commit()
        file_path = os.path.join(UPLOAD_FOLDER, str(new_object.id))
        form.img.data.save(file_path)

        flash('Вы успешно добавили лот')
        return redirect(url_for('/.index'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('lots.adding_lots'))

webapp/user/views.py
from flask_login import login_user, logout_user, current_user
from flask import Blueprint, render_template, flash, redirect, url_for

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('/.index'))

    title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)

            return redirect(url_for('/.index'))

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('/.index'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы вышли')
    return redirect(url_for('/.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('/.index'))
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('user/registration.html', page_title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('/.index'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))

webapp/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{ page_title }}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link href="style.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://m.w3newbie.com/you-tube.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

</head>
<body>
    {% include 'menu.html' %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>




<!-- View in Browser: Drew's #1 Trending YouTube Tutorial -->
<!-- <div class="youtube-tutorial">
	<a href="http://w3n.link/bundle-bonus-playlist" target="_blank" style="cursor: pointer!important;">
    <img src="https://w3newbie.com/wp-content/uploads/12-site-bundle-banner.png" style="max-width: 100%; position: absolute; bottom: 0;">
  </a>
</div> -->
<!-- End View in Browser: Drew's #1 Trending YouTube Tutorial -->

webapp/templates/contact.html
<!DOCTYPE html>
<html>
<head>
    <title>Обратная связь</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<h1>Обратная связь</h1>

<form action="contact.php" method="POST">
<p><input type="text" name="fio" value=""></p>
<p><textarea name="message" rows=10 cols=40></textarea></p>
<p><input type="submit" value="Отправить"></p>
</form>

</body>
</html>

webapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{ title }}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link href="style.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://m.w3newbie.com/you-tube.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

	<style>
		/* Full-width input fields */
		input[type=text], input[type=password] {
		  width: 100%;
		  padding: 12px 20px;
		  margin: 8px 0;
		  display: inline-block;
		  border: 1px solid #ccc;
		  box-sizing: border-box;
		}
		
		/* Set a style for all buttons */
		button {
		  background-color: #b68832;
		  color: white;
		  padding: 14px 20px;
		  margin: 8px 0;
		  border: none;
		  cursor: pointer;
		  width: 100%;
		}
		
		button:hover {
		  opacity: 0.8;
		}
		
		/* Extra styles for the cancel button */
		.cancelbtn {
		  width: auto;
		  padding: 10px 18px;
		  background-color: #99322b;
		}
		
		/* Center the image and position the close button */
		.imgcontainer {
		  text-align: center;
		  margin: 24px 0 12px 0;
		  position: relative;
		}
		
		img.avatar {
		  width: 40%;
		  border-radius: 50%;
		}
		
		.container {
		  padding: 16px;
		}
		
		span.psw {
		  float: right;
		  padding-top: 16px;
		}
		
		/* The Modal (background) */
		.modal {
		  display: none; /* Hidden by default */
		  position: fixed; /* Stay in place */
		  z-index: 1; /* Sit on top */
		  left: 0;
		  top: 0;
		  width: 100%; /* Full width */
		  height: 100%; /* Full height */
		  overflow: auto; /* Enable scroll if needed */
		  background-color: rgb(0,0,0); /* Fallback color */
		  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
		  padding-top: 60px;
		}
		
		/* Modal Content/Box */
		.modal-content {
		  background-color: #fefefe;
		  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
		  border: 1px solid #888;
		  width: 40%; /* Could be more or less, depending on screen size */
		}
		
		/* The Close Button (x) */
		.close {
		  position: absolute;
		  right: 25px;
		  top: 0;
		  color: #000;
		  font-size: 35px;
		  font-weight: bold;
		}
		
		.close:hover,
		.close:focus {
		  color: red;
		  cursor: pointer;
		}
		
		/* Add Zoom Animation */
		.animate {
		  -webkit-animation: animatezoom 0.6s;
		  animation: animatezoom 0.5s;
		}
		
		@-webkit-keyframes animatezoom {
		  from {-webkit-transform: scale(0)} 
		  to {-webkit-transform: scale(1)}
		}
		  
		@keyframes animatezoom {
		  from {transform: scale(0)} 
		  to {transform: scale(1)}
		}
		
		/* Change styles for span and cancel button on extra small screens */
		@media screen and (max-width: 300px) {
		  span.psw {
			 display: block;
			 float: none;
		  }
		  .cancelbtn {
			 width: 100%;
		  }
		}
		</style>

</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-brand" href="#"><img src="static/img/estate_logo_1.jpg"></a>	
	<button class="navbar-toggler" type="button" data-toggle="collapse"
	data-target="#navbarResponsive">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarResponsive">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item active">
				<a class="nav-link" href="#">Домой</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#" onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Войти</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Торговая площадка</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">О нас</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Связаться</a>
			</li>
		</ul>
	</div>

</div>	
</nav>

<div id="id01" class="modal">
  
	<form class="modal-content animate" action="/action_page.php" method="post">
	  <div class="imgcontainer">
		<span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
		<img src="img_avatar2.png" alt="Avatar" class="avatar">
	  </div>
  
	  <div class="container">
		<label for="uname"><b>Логин</b></label>
		<input type="text" placeholder="Введите имя" name="uname" required>
  
		<label for="psw"><b>Пароль</b></label>
		<input type="password" placeholder="Введите пароль" name="psw" required>
		  
		<button type="submit">Войти</button>
		<label>
		  <input type="checkbox" checked="checked" name="remember"> Запомнить меня
		</label>
	  </div>
  
	  <div class="container" style="background-color:#f1f1f1">
		<button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Отмена</button>
		<span class="psw">Забыли <a href="#">пароль?</a></span>
	  </div>
	</form>
</div>

<script>
	// Get the modal
	var modal = document.getElementById('id01');
	
	// When the user clicks anywhere outside of the modal, close it
	window.onclick = function(event) {
		if (event.target == modal) {
			modal.style.display = "none";
		}
	}
</script>

<!--- Image Slider -->
<div id="slides" class="carousel slide" data-ride="carousel">
<ul class="carousel-indicators">
	<li data-target="#slides" data-slide-to="0" class="active"></li>
	<li data-target="#slides" data-slide-to="1"></li>
	<li data-target="#slides" data-slide-to="2"></li>
</ul>
<div class="carousel-inner">
	<div class="carousel-item active">
		<img src="static/img/estate_backgroud.jpg">
		<div class="carousel-caption">
			<h1 class="display-2">Жилье твоей мечты</h1>
			<h3>Аукцион элитной недвижимости</h3>
		</div>
	</div>
	<div class="carousel-item">
		<img src="static/img/real_estate_2.jpg">
	</div>
	<div class="carousel-item">
		<img src="static/img/real_estate_1.jpg">
	</div>
</div>
</div>

<!--- Jumbotron -->
<div class="container-fluid">
<div class="row jumbotron">
	<div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-10">
		<p class="lead">Этот сайтец поможет Михаилу и Антону защитить свой выпускной проект
			курса Learn.Python!
		</p>
	</div>
</div>
</div>
<!--- Welcome Section -->
<div class="container-fluid padding">
<div class="row welcome text-center">
	<div class="col-12">
		<h1 class="display-4">Недвижимость мечты.</h1>
	</div>
	<hr>
	<div class="col-12">
		<p class="lead">Дома, пентхаусы, виллы. Лучшие предложения. Проверенные продавцы. </p>
	</div>
</div>
</div>
<!--- Three Column Section -->
<div class="container-fluid padding">
<div class="row text-center padding">
	<div class="col-xs-12 col-sm-6 col-md-4">
		<img class="house-exmp" src="static/img/house_1.jpg">
		<h3>Дома</h3>
		<p>Классические варианты для тех, кто ценит гармонию</p>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-4">
		<img class="house-exmp" src="static/img/house_3.jpg">
		<h3>Виллы</h3>
		<p>Роскошь и размер для привыкших жить с размахом</p>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-4">
		<img class="house-exmp" src="static/img/house_2.jpg">
		<h3>Пентхаусы</h3>
		<p>Уникальные апартаменты для ищущих уединения в городских джунглях</p>
	</div>
</div>
<hr class="my-4">
</div>

<!--- Two Column Section -->
<div class="container-fluid padding">
<div class="row padding">
	<div class="col-lg-6">
		<h2>Отличная недвижка</h2>
		<p>Пока делается этот фронт Миша дико страдает пытаясь осилить базы данных SQLAlchemy</p>
		<p>Еще один тестовый параграф</p>
		<br>
		<a href="#" class="btn btn-primary">Узнать больше</a></a>
	</div>
	<div class="col-lg-6">
		<img src="static/img/estate_desk.jpg" class="img-fluid">
	</div>
</div>
</div>

<hr class="my-4">
<!--- Fixed background -->
<figure>
	<div class="fixed-wrap">
		<div id="fixed">
		</div>
	</div>
</figure>

<!--- Emoji Section -->

  
<!--- Meet the team -->
<div class="container-fluid padding">
<div class="row welcome text-center">
	<div class="col-12">
		<h1 class="display-4">Наша команда</h1>
	</div>
	<hr>
</div>
</div>
<!--- Cards -->
<div class="container-fluid padding">
<div class="row padding">
	<div class="col-md-4">
		<div class="card">
			<img class="card-img-top" src="static/img/team1.png">
			<div class="card-body">
				<h4 class="card-title">Василий</h4>
				<p class="card-text">Эксперт по продаже элитной недвижимости с более чем 20 годами стажа.</p>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="card">
			<img class="card-img-top" src="static/img/team2.png">
			<div class="card-body">
				<h4 class="card-title">Яна</h4>
				<p class="card-text">Дизайнер с опытом более 5 лет. Поможет оформить ваше обявление в лучшем виде.</p>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="card">
			<img class="card-img-top" src="static/img/team3.png">
			<div class="card-body">
				<h4 class="card-title">Михаил/Антон</h4>
				<p class="card-text">Разработчики с 3.5 неделями опыта. Постарается не уронить сайт пока вы продаете/покупаете дом</p>
			</div>
		</div>
	</div>
</div>
<hr class="my-4">
</div>

<!--- Two Column Section -->


<!--- Connect -->
<div class="container-fluid padding">
<div class="row text-center padding">
	<div class="col-12">
		<h2>Медиа</h2>
	</div>
	<div class="col-12 social padding">
		<a href="#"><i class="fab fa-vk"></i></a>
		<a href="#"><i class="fab fa-instagram"></i></a>
		<a href="#"><i class="fab fa-youtube"></i></a>
	</div>
</div>
</div>
<!--- Footer -->
<footer>
<div class="container-fluid padding">
<div class="row text-center">
	<div class="col-12">
	<h5>Тут могла быть ваша реклама</h5>
	</div>
</div>
</div>
</footer>



</body>
</html>




<!-- View in Browser: Drew's #1 Trending YouTube Tutorial -->
<!-- <div class="youtube-tutorial">
	<a href="http://w3n.link/bundle-bonus-playlist" target="_blank" style="cursor: pointer!important;">
    <img src="https://w3newbie.com/wp-content/uploads/12-site-bundle-banner.png" style="max-width: 100%; position: absolute; bottom: 0;">
  </a>
</div> -->
<!-- End View in Browser: Drew's #1 Trending YouTube Tutorial -->

webapp/templates/menu.html
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><img src="../static/img/estate_logo_1.jpg"></a>	
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Главная</a>
                </li>
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                {% if current_user.is_admin %}
                    <li class="nav-item">
                        <a href="{{ url_for('admin.admin_index') }}" class="nav-link">Управления</a>
                    </li>
                {% endif %}                
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('lots.adding_lots') }}">Добавить лот</a>
                </li>
            {% else %}
                <li class="nav-item">                    
                    <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
                </li> 
            {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('lots.lots') }}">Торговая площадка</a>
                </li>
            </ul>
        </div>    
    </div>	
</nav>