webapp/object/models.py
from webapp.db import db


class Object(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    object_name = db.Column(db.String(200), nullable=False)
    description = db.Column(db.String(1000), nullable=False)
    email = db.Column(db.String(50), nullable=False)
    starting_price = db.Column(db.String(1000), nullable=True)

    def __repr__(self):
        return f'<objects {self.id}>'

webapp/object/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, MultipleFileField, FileField
from wtforms.validators import Email


class AddingLotForm(FlaskForm):
    object_name = StringField('Название лота', render_kw={"textarea class": "form-control"})
    description = StringField(
        'Описание', render_kw={"textarea class": "form-control"}
    )
    img = FileField('Фото', render_kw={"class": "form-control-file"})
    starting_price = StringField('Цена', render_kw={"class": "form-control"})
    email = StringField(
        'Электронная почта', validators=[Email('Некорректный email')], render_kw={"class": "form-control"}
    )
    submit = SubmitField('Отправить!', render_kw={"class": "btn btn-success"})

webapp/object/views.py
import os
from flask import Blueprint, render_template, redirect, url_for, flash
from webapp.object.forms import AddingLotForm
from webapp.db import db
from webapp.object.models import Object
from webapp.user.models import User

blueprint = Blueprint('lots', __name__, url_prefix='/lots')

UPLOAD_FOLDER = './webapp/uploads'

@blueprint.route('/')
def lots():
    page_title = "Лоты на продажу"
    object_list = Object.query.all()
    #object_name = Object.object_name
    #object_description = Object.description
    #object_img = Object.img
    #object_starting_price = Object.starting_price
    #object_email = Object.email
    return render_template('object/lots.html', object_list=object_list, page_title=page_title) #object_name=object_name, object_description=object_description, object_img=object_img, object_starting_price=object_starting_price, object_email=object_email)


@blueprint.route('/adding-lots')
def adding_lots():
    form = AddingLotForm()
    page_title = "Add lots"
    return render_template('object/adding_lots.html', page_title=page_title, form=form)


@blueprint.route('/process-add', methods=['POST'])
def process_add():
    form = AddingLotForm()
    if form.validate_on_submit():
        new_object = Object(object_name=form.object_name.data, description=form.description.data, starting_price=form.starting_price.data, email=form.email.data)
        db.session.add(new_object)
        db.session.commit()
        file_path = os.path.join(UPLOAD_FOLDER, str(new_object.id))
        form.img.data.save(file_path)

        flash('Вы успешно добавили лот')
        return redirect(url_for('/.index'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('lots.adding_lots'))

webapp/user/views.py
from flask_login import login_user, logout_user, current_user
from flask import Blueprint, render_template, flash, redirect, url_for

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('/.index'))

    title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)

            return redirect(url_for('/.index'))

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('/.index'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы вышли')
    return redirect(url_for('/.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('/.index'))
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('user/registration.html', page_title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('/.index'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))

webapp/templates/object/adding_lots.html
{% extends "base.html" %}
  {% block content %}
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}      
    <div class="container">
      <div class="row">
        <div class="col-6">
              
            <form action="{{ url_for('lots.process_add') }}" method="post" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
            <div class="form-group" >
                {{ form.object_name.label }}<br>
                {{ form.object_name() }}
            </div>
            <div class="form-group" >
                {{ form.description.label }}<br>
                {{ form.description() }}
            </div>
            <div class="form-group">
                {{ form.img.label }}<br>
                {{ form.img() }}
            </div>
            <div class="form-group">
                {{ form.starting_price.label }}<br>
                {{ form.starting_price() }}
            </div>
            <div class="form-group">
                {{ form.email.label }}<br>
                {{ form.email() }}
            </div>
            {{ form.submit }}
        </form>
        </div>
    <div class="col-6">

    </div>
    </div>
</div>

{% endblock content %}

webapp/templates/object/lots.html
{% extends 'base.html' %}

{% block content %}
{{ super() }}
<head>
    <title>{{ page_title }}</title>
    <link type="text/css" href="../static/style.css" rel="stylesheet">
</head>
<body>
    <!-- Первый лот -->
{% for obj in object_list %}
<div class="lot">
    <table class="table table-hover" border="0", cellpadding="15", align="center", width="100%">
    <tr>
        <td rowspan="3", width="400", height="200">
            <img src="/uploads/{{ obj.id }}" height="200" width="400" border="1">
        </td>
        <td width="200", style="font-weight: bold">{{ obj.object_name }}</td>
        <td>{{ obj.description }}</td>
    </tr>
    <tr>
        <td><b>Стартовая цена</b></td>
        <td>{{ obj.starting_price }}</td>
    </tr>
    <tr>
        {% if current_user.is_authenticated %}
        <td><b>Контакт продавца</b></td>
        <td>{{ obj.email }}</td>
        {% else %}
        <td><b>Контакт продавца</b></td>
        <td>Чтобы увидеть контакты, <a href="{{ url_for('user.login') }}">авторизуйтесь</a></td>
        {% endif %}
    </tr>
    </table>

</div>
{% endfor %}
</body>
{% endblock %}


<!-- style="border: 1px solid transparent" -->